### ISSUE TITLE
SSH is missing from Docker container

### ISSUE THREAD

**Issue by m13t** [charmbracelet/soft-serve#264]
**Describe the bug**
SSH is missing from the docker container. This is preventing importing/mirroring git repositories over SSH

**To Reproduce**
Try import repository using git:// or ssh:// protocols

**Expected behavior**
SSH should be packaged with container image

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Docker

**Additional context**
N/A

**Comment by m13t** [comment]
I'm happy to create a PR for this.

**Comment by aymanbagabas** [comment]
@m13t PRs are welcome. A better solution is to switch to using [go-git](https://pkg.go.dev/github.com/go-git/go-git/v5#CloneOptions) to import repositories.

**Comment by m13t** [comment]
I saw there was some history about go-git. It was used previously right but removed due to some issues? I'll push a PR in for the docker image as a quick fix. Pretty small footprint on alpine.

**Comment by aymanbagabas** [comment]
> I saw there was some history about go-git. It was used previously right but removed due to some issues?

That's correct, there were issues with memory management after loading multiple repositories. Hopefully, these issues were fixed in Go-git v5.6.

When it comes to server-side, Go-git sadly needs a lot of work to support a pure-go server-side implementation of git. Specifically git service commands. Last time I checked, go-git only supports git-protocol v0 and only supports a few git capabilities. It also lacks support for `git-upload-archive` service.

The goal is to implement that in go-git someday, use go-git in soft-serve, and remove external dependencies like git, ssh, and bash 🙂
