### ISSUE TITLE
Support mirroring for private repos

### ISSUE THREAD

**Issue by nicolas-g** [charmbracelet/soft-serve#296]
**Is your feature request related to a problem? Please describe.**
Mirroring is only supported on public repos

**Describe the solution you'd like**
Add support for mirroring private repos

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by caarlos0** [comment]
FWIW you can mirror using the github https url and a github token: `https://$TOKEN@github.com/owner/repo.git`

**Comment by nicolas-g** [comment]
Hi @caarlos0 , when I try the above with the import command I get an error:

```bash
ssh localhost -p 23231 repo import myrepo https://$GITHUB_OAUTH_TOKEN:github.com/$ORG/$REPO.git

Error: exit status 128 - fatal: unable to access 'https://github_pat_XXXYYYZZZ:github.com/MyOrg/myrepo.git/': URL using bad/illegal format or missing URL
```

**Comment by caarlos0** [comment]
You have a : instead of a @ there

**Comment by nicolas-g** [comment]
thank you @caarlos0  , this worked .

**Comment by bashbunni** [comment]
@caarlos0 @aymanbagabas Should we document this as a solution for mirroring private repos or is there some kind of built-in support you'd like to integrate to Soft Serve?

**Comment by caarlos0** [comment]
I think we should allow to use a specific ssh key, so we don't store the token in the db, or, at the very least, we should support environment variable substitution in the urls

**Comment by aymanbagabas** [comment]
You can specify your own SSH `client_key_path` in the config, this key is used when importing repositories over SSH. You can also specify that using environment variables, refer to [server settings](https://github.com/charmbracelet/soft-serve#server-settings) for more info.
Closing this as resolved

**Comment by nwithan8** [comment]
> You can specify your own SSH `client_key_path` in the config, this key is used when importing repositories over SSH. You can also specify that using environment variables, refer to [server settings](https://github.com/charmbracelet/soft-serve?rgh-link-date=2023-05-25T13%3A26%3A39.000Z#server-settings) for more info. Closing this as resolved

This is not currently working for me (v0.8.2). I have added the public key `ssh/soft_serve_client_ed25519` to my GitHub SSH keychain, and my config file (ssh.client_key_path) is pointing to the private equivalent.

When trying to clone/mirror a private repo (`repo import --mirror notes https://github.com/nwithan8/notes`), the CLI hangs and the logs say the following:

```
2025-01-31 18:34:54 INFO backend: importing repository name=notes remote=https://github.com/nwithan8/notes path=/soft-serve/repos/notes.git
2025-01-31 18:34:54 INFO backend: running import name=notes
2025-01-31 18:34:54 ERRO backend: failed to clone repository
  err=
  │ exit status 128 - fatal: could not read Username for 'https://github.com': No such device or address
 mirror=true remote=https://github.com/nwithan8/notes path=/soft-serve/repos/notes.git
```

**Comment by aymanbagabas** [comment]
> This is not currently working for me (v0.8.2). I have added the public key `ssh/soft_serve_client_ed25519.pub` to my GitHub SSH keychain, and my config file (ssh.client_key_path) is pointing to the private equivalent.
> 
> When trying to clone/mirror a private repo (`repo import --mirror notes https://github.com/nwithan8/notes`), the CLI hangs and the logs say the following:
> 
> ```
> 2025-01-31 18:34:54 INFO backend: importing repository name=notes remote=https://github.com/nwithan8/notes path=/soft-serve/repos/notes.git
> 2025-01-31 18:34:54 INFO backend: running import name=notes
> 2025-01-31 18:34:54 ERRO backend: failed to clone repository
>   err=
>   │ exit status 128 - fatal: could not read Username for 'https://github.com': No such device or address
>  mirror=true remote=https://github.com/nwithan8/notes path=/soft-serve/repos/notes.git
> ```

Hi @nwithan8 🙂 

Here, you’re trying to clone a private repository over HTTP. In that case, mirroring is even simpler using your GitHub token as a basic auth.

```sh
repo import --mirror notes https://$MY_PERSONAL_ACESS_TOKEN@github.com/nwithan8/notes
```

Now, internally, the repository remote url _will_ contain the token and any updates can be pulled as long as the token is valid and not expired.

To mirror a private repository over SSH, you need to use ssh.client_key configuration, like what you already doing, _and_ use an SSH clone url.

```sh
repo import --mirror notes git@github.com:nwithan8/notes

# or

repo import --mirror notes ssh://git@github.com/nwithan8/notes
```

**Comment by twhite96** [comment]
Can we mirror from more services than GitHub, like Gitea or Forgejo? Same type of protocol so not sure if it's the same process. Love your work, building a TUI with it as we speak.

**Comment by aymanbagabas** [comment]
> Can we mirror from more services than GitHub, like Gitea or Forgejo? Same type of protocol so not sure if it's the same process. Love your work, building a TUI with it as we speak.

Hi @twhite96 👋 

Mirroring in Soft Serve work the same way across different git hosting providers. Though, it varies by the protocol. 

Soft Serve supports serving and mirroring from Git TCP, SSH, and HTTP(s). The Git protocol (port 9418) doesn't require authentication and thus mirroring is as simple as `ssh mysoftserver repo mirror newrepo git://gitprovider/newrepo.git`. However, some providers like GitHub and GitLab don't support this insecure protocol.

Then there's the SSH approach which requires public keys to import repositories. Soft Serve will use the client key defined in your config (or using environment variables). You can generate a new SSH key specifically for mirroring repositories, add that key to your git hosting provider, and define it in your Soft Serve config. Then you can mirror repositories using 
`ssh mysoftserver repo mirror newrepo ssh://gitprovider/newrepo.git` which would use the Soft Serve client key to clone and update the repository.

Now for HTTP, git supports basic http authentication. This means cloning a private repository should work using something like `ssh mysoftserver repo mirror newrepo https://username:password@gitprovider/newrepo.git`. However, most if not all providers disallow using username and password to clone repositories due to the weak security measures of basic auth. You can still use access tokens in place of the username argument to get access to the repository. GitHub and GitLab support creating  access tokens that you can use to mirror repositories with Soft Serve. Simply use the access tokens in your import url `ssh mysoftserver repo mirror newrepo https://accesstoken@gitprovider/newrepo.git`. Keep in mind that this method *will* expose the access tokens as plain text in the mirrored repository's git config under your Soft Serve data directory.

I hope this helps explain how these different protocols work with conjunction with Soft Serve 🙂
